@display_configuration.sql



BREAK ON TABLESPACE_NAME ON USED_PERCENT

select
x.TABLESPACE_NAME,
y.USED_PERCENT,
x.FILE_NAME,
x.TOTGO,
x.STATUS,
x.AUTOEXTENSIBLE,
x.MAXEXTGO
from (
select 
TABLESPACE_NAME,
FILE_NAME,
BYTES/1024/1024/1024 TOTGO,
STATUS,
AUTOEXTENSIBLE,
MAXBYTES/1024/1024/1024 MAXEXTGO
from dba_data_files
union all
select
TABLESPACE_NAME,
FILE_NAME,
BYTES/1024/1024/1024 TOTGO,
STATUS,
AUTOEXTENSIBLE,
MAXBYTES/1024/1024/1024 MAXEXTGO
from dba_temp_files
) x,
DBA_TABLESPACE_USAGE_METRICS y
where x.TABLESPACE_NAME = y.TABLESPACE_NAME
order by USED_PERCENT desc ;
