@display_configuration.sql

col BEGIN_INTERVAL_TIME format a25
col INSTANCE_NUMBER format 9999
col PLAN_HASH_VALUE format 999999999999
col PARSING_SCHEMA_NAME format a20
col EXECUTIONS_DELTA format 999999999999
col ROWS_PROCESSED_DELTA format 999999999999
col AVG_ROWS_PROCESSED_BY_EXEC format 999999999999.99
col ELAPSED_TIME_DELTA format 9999999999.99
col AVG_ELAPSED_TIME_BY_EXEC format 9999999999.9999

select
trunc(BEGIN_INTERVAL_TIME,'MI'),
PLAN_HASH_VALUE,
PARSING_SCHEMA_NAME,
sum(EXECUTIONS_DELTA),
sum(ELAPSED_TIME_DELTA)/1000000 ELAPSED_TIME_DELTA,
sum(ELAPSED_TIME_DELTA)/sum(EXECUTIONS_DELTA)/1000000 AVG_ELAPSED_TIME_BY_EXEC,
sum(ROWS_PROCESSED_DELTA)/sum(EXECUTIONS_DELTA) AVG_ROWS_PROCESSED_BY_EXEC
from DBA_HIST_SQLSTAT x,
DBA_HIST_SNAPSHOT y
where x.SNAP_ID = y.SNAP_ID
and x.DBID = y.DBID
and x.INSTANCE_NUMBER = y.INSTANCE_NUMBER
and sql_id = '&sql_id.'
and BEGIN_INTERVAL_TIME >= sysdate - 5
group by trunc(BEGIN_INTERVAL_TIME,'MI'),
PLAN_HASH_VALUE,
PARSING_SCHEMA_NAME
order by 1
;
